[package]
name = "discord-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "*"
tracing-subscriber = "*"
tracing-futures = "*"

rand = "*"
songbird = "*"

[dependencies.serenity]
version = "0.10.9"
features = [ "cache", "framework", "standard_framework", "voice", "http", "rustls_backend"]

[dependencies.tokio]
version = "*"
features = ["macros","rt-multi-thread", "signal"]


[profile.dev]
opt-level=1

[profile.release]
opt-level=3
